### PR TITLE
No need to require nightly anymore

### PR DESCRIPTION
**Pull request by zeenix**
The underlying [issue](https://github.com/Rahix/avr-hal/issues/124) in avr-hal has been fixed.

---

P.S. Thanks so much for creating this crate. I recently got into microcontroller programming and was banging my head against the other crates but didn't get anywhere. With your crates, I just copy&paste, update the pins and tada, it works. \o/

### CODE REVIEW

**Comment by zeenix** [comment]
Ughh.. I should have tested before jumping the gun. :) Nightly is still required. However, I think we should still update the wording in the README. I'll update the PR..

**Comment by zeenix** [comment]
> I'll update the PR..

Nm, should be a separate PR. Sorry for the noise.

**Comment by mjhouse** [comment]
@zeenix It's fine! thanks for using the crate. Feel free to improve it however you like- I'll try to review and merge PRs as quickly as possible.

**Comment by zeenix** [comment]
Cool. I think I'll have a look into #22 after I'm back from vacation I just started. 😊 I'm very new to all this though so if you could give some pointers or hints (if possible) on #22, that would be super helpful. 👍

**Comment by mjhouse** [comment]
Will do. Give me a chance to look at it.

**Comment by zeenix** [comment]
>  Will do. 

Many thanks.

> Give me a chance to look at it.

Sure thing. I'm still on vacation till next week so there's absolutely no hurry. 😊

**Pull request closed without merging**
