### PR TITLE
Update to embedded-hal 1.0.0

### PR DESCRIPTION
**Pull request by tomried**
Update to embedded-hal 1.0.0 and port-expander 0.6.2. Embedded-hal 1.0.0 has breaking changes from 0.2.3, but is the first stable release without any further breaking changes. Should work without problems for any hal implementing embedded-hal 1.0.0 traits. 
Tested with an esp32s3 and a 20x4 LCD interfaced via i2c.

### CODE REVIEW

**Comment by mjhouse** [comment]
This looks fine, but fill out the PR description with a description of the changes and rational before I merge it.

**Comment by tomried** [comment]
Updated the description. I think the adoption of embedded-hal 1.0 is quite far with hals to update this crate without providing a backwards-compatible optional feature, what do you think?

**Comment by mjhouse** [comment]
> Updated the description. I think the adoption of embedded-hal 1.0 is quite far with hals to update this crate without providing a backwards-compatible optional feature, what do you think?

I'm not sure I understand. Are you asking if this PR breaks *our* backward compatibility?

**Comment by tomried** [comment]
This PR breaks backwards compatibility with hals depending on embedded-hal versions lower than 1.0. I was asking if you think that's a problem. I don't think so, because the hals I have seen have been updated to 1.0, and older hals can use the older version of our crate.

**Comment by mjhouse** [comment]
Ah yeah. I don't think it's a big deal either.

**Pull request merged**
